### ISSUE TITLE
automate

### ISSUE THREAD

**Issue by FranklinYu** [jsok/docker-for-mac-versions#2]
Possibly helpful resources:

* [Travis-CI cron jobs](https://docs.travis-ci.com/user/cron-jobs/) which [uses virtualenv implicitly](https://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs).
* Encrypt GitHub API key with [Travis asymmetric encryption](https://docs.travis-ci.com/user/encryption-keys/).
* Possibly avoid any system call by using [pygit2](http://www.pygit2.org/).

**Comment by jsok** [comment]
Cheers for the links. I've created a `.travis.yml` and got it successfully building and running. The main issue at the moment is that it takes a long time to scrape all ~20,000 build IDs.

I think I'm going to have to work on an incremental solution which runs nightly and scrapes a smaller range of IDs and merges the build info into the [JSON data files](https://github.com/jsok/docker-for-mac-versions/tree/gh-pages/_data).

**Comment by FranklinYu** [comment]
Actually I'm thinking about starting from the last build from current JSON in `gh-pages` branch (and that's why I mentioned Git and encryption). After scraping, just push to this branch with updated JSON (maybe begin the commit message with "[bot]").

**Comment by FranklinYu** [comment]
Closing this issue, since Docker team now provides it officially.
